# Generated by Django 4.2 on 2024-04-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(blank=True, max_length=255, null=True)),
                ('article_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('article_child_options', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tag_name', models.CharField(blank=True, max_length=255, null=True)),
                ('article_tag_name_eng', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_productnumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('video_views', models.IntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_image', models.CharField(blank=True, max_length=1023, null=True)),
                ('video_images', models.CharField(blank=True, max_length=1023, null=True)),
                ('video_sumple_video', models.URLField(blank=True, null=True)),
                ('video_issue', models.DateField(blank=True, null=True)),
                ('video_affiliateurl', models.URLField(blank=True, null=True)),
                ('video_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serializer.label')),
                ('video_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serializer.maker')),
                ('video_performers', models.ManyToManyField(blank=True, null=True, to='serializer.performer')),
                ('video_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serializer.series')),
                ('video_tags', models.ManyToManyField(blank=True, null=True, related_name='video_tags', to='serializer.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teststr', models.CharField(blank=True, max_length=255, null=True)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serializer.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_num', models.IntegerField(blank=True, null=True)),
                ('article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_title_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('article_post_day', models.DateField()),
                ('article_explain', models.CharField(blank=True, max_length=1023, null=True)),
                ('article_views', models.IntegerField(blank=True, null=True)),
                ('article_options', models.JSONField()),
                ('article_childlen', models.ManyToManyField(blank=True, null=True, related_name='article_child_article_childlen', to='serializer.article_child')),
                ('article_images', models.ManyToManyField(blank=True, null=True, related_name='article_child_article_images', to='serializer.article_child')),
                ('article_tags', models.ManyToManyField(blank=True, null=True, to='serializer.article_tag')),
            ],
        ),
    ]
