# Generated by Django 4.2 on 2024-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_options_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
