# Generated by Django 4.2 on 2024-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0002_article_article_options_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_images',
        ),
        migrations.AddField(
            model_name='video',
            name='video_postday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_post_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
