# Generated by Django 4.2 on 2024-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0003_remove_article_article_images_video_video_postday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
