# Generated by Django 4.2 on 2024-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0004_article_article_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_child',
            name='article_title_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
