# Generated by Django 4.2 on 2024-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0005_article_child_article_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
