# Generated by Django 4.2 on 2024-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0006_alter_article_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_options_explain',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
