# Generated by Django 4.2 on 2024-07-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0007_article_article_options_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_affiliate_char1',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_affiliate_char2',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_affiliate_char3',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_affiliate_char4',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
