# Generated by Django 4.2 on 2024-07-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0008_video_video_affiliate_char1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_affiliate_char1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_affiliate_char2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_affiliate_char3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_affiliate_char4',
        ),
        migrations.AddField(
            model_name='article_child',
            name='article_affiliate_urls',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
